server:
  ssl:
    key-store: classpath:mykey.p12
    key-store-password: 123456
    key-store-type: pkcs12
    key-alias: mykey
  port: 8443
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/login_template_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: 123

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 446507789815-j93jk6lnud8etj8sjbds849uccrpsijh.apps.googleusercontent.com
              client-secret: dG9Zuh5k0GTl6GBr4vMxFKIj
              scope:
                - email
                - profile
            facebook:
              clientId: 536118074130689
              clientSecret: 168be6cbd343a7b95c5d39e163971941
              scope:
                - email
                - public_profile
            github:
              clientId: 2e1d20b8e176d878c0f3
              clientSecret: 7eac4800bd789fce647aa1d6b8a8d8aef018e752
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    token:
      secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
      expirationMsc: 864000000
    cookie:
      name: token
      expirationSec: 36000
  cors:
    allowedOrigins: https://localhost:8443
